name: nightly-sdk-generation
"on":
  schedule:
    - cron: 35 4 * * 1-5
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PROVIDER: google-native

jobs:
  generate-sdk:
    name: prerequisites
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [1.17.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Cleanup SDK folder
        run: make clean
      - name: Preparing Git Branch
        run: |
          git config --local user.email "bot@pulumi.com"
          git config --local user.name "pulumi-bot"
          git checkout -b generate-sdk/${{ github.run_id }}-${{ github.run_number }}
      - name: Commit empty SDK
        run: |
          git add .
          git commit -m "Preparing the SDK folder for regeneration"
          git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
      - name: Discovery
        id: discovery
        run: |
          make discovery
          git update-index -q --refresh
          if ! git diff-files --quiet; then
            echo ::set-output name=changes::1
          fi
      - name: Build codegen binaries
        if: steps.discovery.outputs.changes != 0
        run: make codegen
      - name: Build Schema + SDKs
        if: steps.discovery.outputs.changes != 0
        run: make local_generate
      - name: Commit changes
        if: steps.discovery.outputs.changes != 0
        run: |
          git add discovery
          git commit -m "Discovery documents"
          git add .
          git commit -m "Regenerating SDKs based on updated modules"
          git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
          git checkout master
      - name: Create PR
        id: create-pr
        if: steps.discovery.outputs.changes != 0
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "generate-sdk/${{ github.run_id }}-${{ github.run_number }}"
          title: "Automated SDK generation"
          body: ""
          labels: impact/no-changelog-required
          committer: pulumi-bot <bot@pulumi.com>
          author: pulumi-bot <bot@pulumi.com>
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Set Automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          repository: ${{ github.repository }}
          merge-method: squash
